project_id = "dsmndlilrykwnshhsszz"

[functions.send-assignment-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.hail-report]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false